---
abstract: 'A plugin bundle for distributions built by ZMUGHAL'
author:
  - 'Zakariyya Mughal <zmughal@cpan.org>'
build_requires:
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.024, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-PluginBundle-Author-ZMUGHAL
no_index:
  directory:
    - eg
    - examples
    - inc
    - share
    - t
    - xt
requires:
  App::scan_prereqs_cpanfile: '0'
  Dist::Zilla::Plugin::AutoPrereqs: '0'
  Dist::Zilla::Plugin::CheckChangeLog: '0'
  Dist::Zilla::Plugin::Git: '0'
  Dist::Zilla::Plugin::Git::CommitBuild: '0'
  Dist::Zilla::Plugin::GithubMeta: '0'
  Dist::Zilla::Plugin::MetaJSON: '0'
  Dist::Zilla::Plugin::MetaNoIndex: '0'
  Dist::Zilla::Plugin::MinimumPerl: '0'
  Dist::Zilla::Plugin::PkgVersion: '0'
  Dist::Zilla::Plugin::PodCoverageTests: '0'
  Dist::Zilla::Plugin::PodWeaver: '0'
  Dist::Zilla::Plugin::ReadmeAnyFromPod: '0'
  Dist::Zilla::Plugin::RunExtraTests: '0'
  Dist::Zilla::Plugin::Test::Perl::Critic: '0'
  Dist::Zilla::Plugin::Test::PodSpelling: '0'
  Dist::Zilla::Role::PluginBundle::Config::Slicer: '0'
  Dist::Zilla::Role::PluginBundle::Easy: '0'
  Dist::Zilla::Role::PluginBundle::PluginRemover: '0.103'
  Moose: '0'
  Perl::Critic::Policy::CodeLayout::TabIndentSpaceAlign: '0'
  Pod::Coverage: '0'
  Pod::Coverage::TrustPod: '0'
  Pod::Elemental::Transformer::List: '0'
  Pod::Weaver::Config::Assembler: '0'
  Pod::Weaver::Section::Consumes: '0'
  Pod::Weaver::Section::Extends: '0'
  Test::Perl::Critic: '0'
  Test::Pod::Coverage: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  homepage: https://github.com/zmughal-CPAN/p5-Dist-Zilla-PluginBundle-Author-ZMUGHAL
  repository: https://github.com/zmughal-CPAN/p5-Dist-Zilla-PluginBundle-Author-ZMUGHAL.git
version: '0.005'
x_generated_by_perl: v5.26.1
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
